const flights = [
    {
        "flightNumber": "PX101",
        "airline": "Phoenix Airlines",
        "source": "Chennai",
        "destination": "Bangalore",
        "departureTime": "06:00 AM",
        "arrivalTime": "07:00 AM",
        "date": "2026-09-20",
        "price": 2000,
        "availableSeats": 10
    },
    {
        "flightNumber": "PX102",
        "airline": "Phoenix Airlines",
        "source": "Delhi",
        "destination": "Hyderabad",
        "departureTime": "07:15 AM",
        "arrivalTime": "08:45 AM",
        "date": "2026-09-21",
        "price": 2175,
        "availableSeats": 15
    },
    {
        "flightNumber": "PX103",
        "airline": "Phoenix Airlines",
        "source": "Mumbai",
        "destination": "Kolkata",
        "departureTime": "08:30 AM",
        "arrivalTime": "10:30 AM",
        "date": "2026-09-22",
        "price": 2350,
        "availableSeats": 20
    },
    {
        "flightNumber": "PX104",
        "airline": "Phoenix Airlines",
        "source": "Bangalore",
        "destination": "Pune",
        "departureTime": "09:45 AM",
        "arrivalTime": "12:15 PM",
        "date": "2026-09-23",
        "price": 2525,
        "availableSeats": 25
    },
    {
        "flightNumber": "PX105",
        "airline": "Phoenix Airlines",
        "source": "Hyderabad",
        "destination": "Goa",
        "departureTime": "11:00 AM",
        "arrivalTime": "02:00 PM",
        "date": "2026-09-24",
        "price": 2700,
        "availableSeats": 30
    },
    {
        "flightNumber": "PX106",
        "airline": "Phoenix Airlines",
        "source": "Kolkata",
        "destination": "Ahmedabad",
        "departureTime": "12:15 PM",
        "arrivalTime": "03:45 PM",
        "date": "2026-09-25",
        "price": 2875,
        "availableSeats": 35
    },
    {
        "flightNumber": "PX107",
        "airline": "Phoenix Airlines",
        "source": "Pune",
        "destination": "Jaipur",
        "departureTime": "01:30 PM",
        "arrivalTime": "02:30 PM",
        "date": "2026-09-26",
        "price": 3050,
        "availableSeats": 40
    },
    {
        "flightNumber": "PX108",
        "airline": "Phoenix Airlines",
        "source": "Goa",
        "destination": "Kochi",
        "departureTime": "02:45 PM",
        "arrivalTime": "04:15 PM",
        "date": "2026-09-27",
        "price": 3225,
        "availableSeats": 45
    },
    {
        "flightNumber": "PX109",
        "airline": "Phoenix Airlines",
        "source": "Ahmedabad",
        "destination": "Lucknow",
        "departureTime": "04:00 PM",
        "arrivalTime": "06:00 PM",
        "date": "2026-09-28",
        "price": 3400,
        "availableSeats": 10
    },
    {
        "flightNumber": "PX110",
        "airline": "Phoenix Airlines",
        "source": "Jaipur",
        "destination": "Chennai",
        "departureTime": "05:15 PM",
        "arrivalTime": "07:45 PM",
        "date": "2026-09-29",
        "price": 3575,
        "availableSeats": 15
    },
    {
        "flightNumber": "PX111",
        "airline": "Phoenix Airlines",
        "source": "Kochi",
        "destination": "Delhi",
        "departureTime": "06:30 PM",
        "arrivalTime": "09:30 PM",
        "date": "2026-09-20",
        "price": 3750,
        "availableSeats": 20
    },
    {
        "flightNumber": "PX112",
        "airline": "Phoenix Airlines",
        "source": "Lucknow",
        "destination": "Mumbai",
        "departureTime": "08:00 PM",
        "arrivalTime": "11:30 PM",
        "date": "2026-09-21",
        "price": 3925,
        "availableSeats": 25
    },
    {
        "flightNumber": "PX113",
        "airline": "Phoenix Airlines",
        "source": "Chennai",
        "destination": "Bangalore",
        "departureTime": "06:00 AM",
        "arrivalTime": "07:00 AM",
        "date": "2026-09-22",
        "price": 4100,
        "availableSeats": 30
    },
    {
        "flightNumber": "PX114",
        "airline": "Phoenix Airlines",
        "source": "Delhi",
        "destination": "Hyderabad",
        "departureTime": "07:15 AM",
        "arrivalTime": "08:45 AM",
        "date": "2026-09-23",
        "price": 4275,
        "availableSeats": 35
    },
    {
        "flightNumber": "PX115",
        "airline": "Phoenix Airlines",
        "source": "Mumbai",
        "destination": "Kolkata",
        "departureTime": "08:30 AM",
        "arrivalTime": "10:30 AM",
        "date": "2026-09-24",
        "price": 4450,
        "availableSeats": 40
    },
    {
        "flightNumber": "PX116",
        "airline": "Phoenix Airlines",
        "source": "Bangalore",
        "destination": "Pune",
        "departureTime": "09:45 AM",
        "arrivalTime": "12:15 PM",
        "date": "2026-09-25",
        "price": 4625,
        "availableSeats": 45
    },
    {
        "flightNumber": "PX117",
        "airline": "Phoenix Airlines",
        "source": "Hyderabad",
        "destination": "Goa",
        "departureTime": "11:00 AM",
        "arrivalTime": "02:00 PM",
        "date": "2026-09-26",
        "price": 4800,
        "availableSeats": 10
    },
    {
        "flightNumber": "PX118",
        "airline": "Phoenix Airlines",
        "source": "Kolkata",
        "destination": "Ahmedabad",
        "departureTime": "12:15 PM",
        "arrivalTime": "03:45 PM",
        "date": "2026-09-27",
        "price": 4975,
        "availableSeats": 15
    },
    {
        "flightNumber": "PX119",
        "airline": "Phoenix Airlines",
        "source": "Pune",
        "destination": "Jaipur",
        "departureTime": "01:30 PM",
        "arrivalTime": "02:30 PM",
        "date": "2026-09-28",
        "price": 5150,
        "availableSeats": 20
    },
    {
        "flightNumber": "PX120",
        "airline": "Phoenix Airlines",
        "source": "Goa",
        "destination": "Kochi",
        "departureTime": "02:45 PM",
        "arrivalTime": "04:15 PM",
        "date": "2026-09-29",
        "price": 5325,
        "availableSeats": 25
    },
    {
        "flightNumber": "PX121",
        "airline": "Phoenix Airlines",
        "source": "Ahmedabad",
        "destination": "Lucknow",
        "departureTime": "04:00 PM",
        "arrivalTime": "06:00 PM",
        "date": "2026-09-20",
        "price": 2000,
        "availableSeats": 30
    },
    {
        "flightNumber": "PX122",
        "airline": "Phoenix Airlines",
        "source": "Jaipur",
        "destination": "Chennai",
        "departureTime": "05:15 PM",
        "arrivalTime": "07:45 PM",
        "date": "2026-09-21",
        "price": 2175,
        "availableSeats": 35
    },
    {
        "flightNumber": "PX123",
        "airline": "Phoenix Airlines",
        "source": "Kochi",
        "destination": "Delhi",
        "departureTime": "06:30 PM",
        "arrivalTime": "09:30 PM",
        "date": "2026-09-22",
        "price": 2350,
        "availableSeats": 40
    },
    {
        "flightNumber": "PX124",
        "airline": "Phoenix Airlines",
        "source": "Lucknow",
        "destination": "Mumbai",
        "departureTime": "08:00 PM",
        "arrivalTime": "11:30 PM",
        "date": "2026-09-23",
        "price": 2525,
        "availableSeats": 45
    },
    {
        "flightNumber": "PX125",
        "airline": "Phoenix Airlines",
        "source": "Chennai",
        "destination": "Bangalore",
        "departureTime": "06:00 AM",
        "arrivalTime": "07:00 AM",
        "date": "2026-09-24",
        "price": 2700,
        "availableSeats": 10
    },
    {
        "flightNumber": "PX126",
        "airline": "Phoenix Airlines",
        "source": "Delhi",
        "destination": "Hyderabad",
        "departureTime": "07:15 AM",
        "arrivalTime": "08:45 AM",
        "date": "2026-09-25",
        "price": 2875,
        "availableSeats": 15
    },
    {
        "flightNumber": "PX127",
        "airline": "Phoenix Airlines",
        "source": "Mumbai",
        "destination": "Kolkata",
        "departureTime": "08:30 AM",
        "arrivalTime": "10:30 AM",
        "date": "2026-09-26",
        "price": 3050,
        "availableSeats": 20
    },
    {
        "flightNumber": "PX128",
        "airline": "Phoenix Airlines",
        "source": "Bangalore",
        "destination": "Pune",
        "departureTime": "09:45 AM",
        "arrivalTime": "12:15 PM",
        "date": "2026-09-27",
        "price": 3225,
        "availableSeats": 25
    },
    {
        "flightNumber": "PX129",
        "airline": "Phoenix Airlines",
        "source": "Hyderabad",
        "destination": "Goa",
        "departureTime": "11:00 AM",
        "arrivalTime": "02:00 PM",
        "date": "2026-09-28",
        "price": 3400,
        "availableSeats": 30
    },
    {
        "flightNumber": "PX130",
        "airline": "Phoenix Airlines",
        "source": "Kolkata",
        "destination": "Ahmedabad",
        "departureTime": "12:15 PM",
        "arrivalTime": "03:45 PM",
        "date": "2026-09-29",
        "price": 3575,
        "availableSeats": 35
    },
    {
        "flightNumber": "PX131",
        "airline": "Phoenix Airlines",
        "source": "Pune",
        "destination": "Jaipur",
        "departureTime": "01:30 PM",
        "arrivalTime": "02:30 PM",
        "date": "2026-09-20",
        "price": 3750,
        "availableSeats": 40
    },
    {
        "flightNumber": "PX132",
        "airline": "Phoenix Airlines",
        "source": "Goa",
        "destination": "Kochi",
        "departureTime": "02:45 PM",
        "arrivalTime": "04:15 PM",
        "date": "2026-09-21",
        "price": 3925,
        "availableSeats": 45
    },
    {
        "flightNumber": "PX133",
        "airline": "Phoenix Airlines",
        "source": "Ahmedabad",
        "destination": "Lucknow",
        "departureTime": "04:00 PM",
        "arrivalTime": "06:00 PM",
        "date": "2026-09-22",
        "price": 4100,
        "availableSeats": 10
    },
    {
        "flightNumber": "PX134",
        "airline": "Phoenix Airlines",
        "source": "Jaipur",
        "destination": "Chennai",
        "departureTime": "05:15 PM",
        "arrivalTime": "07:45 PM",
        "date": "2026-09-23",
        "price": 4275,
        "availableSeats": 15
    },
    {
        "flightNumber": "PX135",
        "airline": "Phoenix Airlines",
        "source": "Kochi",
        "destination": "Delhi",
        "departureTime": "06:30 PM",
        "arrivalTime": "09:30 PM",
        "date": "2026-09-24",
        "price": 4450,
        "availableSeats": 20
    },
    {
        "flightNumber": "PX136",
        "airline": "Phoenix Airlines",
        "source": "Lucknow",
        "destination": "Mumbai",
        "departureTime": "08:00 PM",
        "arrivalTime": "11:30 PM",
        "date": "2026-09-25",
        "price": 4625,
        "availableSeats": 25
    },
    {
        "flightNumber": "PX137",
        "airline": "Phoenix Airlines",
        "source": "Chennai",
        "destination": "Bangalore",
        "departureTime": "06:00 AM",
        "arrivalTime": "07:00 AM",
        "date": "2026-09-26",
        "price": 4800,
        "availableSeats": 30
    },
    {
        "flightNumber": "PX138",
        "airline": "Phoenix Airlines",
        "source": "Delhi",
        "destination": "Hyderabad",
        "departureTime": "07:15 AM",
        "arrivalTime": "08:45 AM",
        "date": "2026-09-27",
        "price": 4975,
        "availableSeats": 35
    },
    {
        "flightNumber": "PX139",
        "airline": "Phoenix Airlines",
        "source": "Mumbai",
        "destination": "Kolkata",
        "departureTime": "08:30 AM",
        "arrivalTime": "10:30 AM",
        "date": "2026-09-28",
        "price": 5150,
        "availableSeats": 40
    },
    {
        "flightNumber": "PX140",
        "airline": "Phoenix Airlines",
        "source": "Bangalore",
        "destination": "Pune",
        "departureTime": "09:45 AM",
        "arrivalTime": "12:15 PM",
        "date": "2026-09-29",
        "price": 5325,
        "availableSeats": 45
    },
    {
        "flightNumber": "PX141",
        "airline": "Phoenix Airlines",
        "source": "Hyderabad",
        "destination": "Goa",
        "departureTime": "11:00 AM",
        "arrivalTime": "02:00 PM",
        "date": "2026-09-20",
        "price": 2000,
        "availableSeats": 10
    },
    {
        "flightNumber": "PX142",
        "airline": "Phoenix Airlines",
        "source": "Kolkata",
        "destination": "Ahmedabad",
        "departureTime": "12:15 PM",
        "arrivalTime": "03:45 PM",
        "date": "2026-09-21",
        "price": 2175,
        "availableSeats": 15
    },
    {
        "flightNumber": "PX143",
        "airline": "Phoenix Airlines",
        "source": "Pune",
        "destination": "Jaipur",
        "departureTime": "01:30 PM",
        "arrivalTime": "02:30 PM",
        "date": "2026-09-22",
        "price": 2350,
        "availableSeats": 20
    },
    {
        "flightNumber": "PX144",
        "airline": "Phoenix Airlines",
        "source": "Goa",
        "destination": "Kochi",
        "departureTime": "02:45 PM",
        "arrivalTime": "04:15 PM",
        "date": "2026-09-23",
        "price": 2525,
        "availableSeats": 25
    },
    {
        "flightNumber": "PX145",
        "airline": "Phoenix Airlines",
        "source": "Ahmedabad",
        "destination": "Lucknow",
        "departureTime": "04:00 PM",
        "arrivalTime": "06:00 PM",
        "date": "2026-09-24",
        "price": 2700,
        "availableSeats": 30
    },
    {
        "flightNumber": "PX146",
        "airline": "Phoenix Airlines",
        "source": "Jaipur",
        "destination": "Chennai",
        "departureTime": "05:15 PM",
        "arrivalTime": "07:45 PM",
        "date": "2026-09-25",
        "price": 2875,
        "availableSeats": 35
    },
    {
        "flightNumber": "PX147",
        "airline": "Phoenix Airlines",
        "source": "Kochi",
        "destination": "Delhi",
        "departureTime": "06:30 PM",
        "arrivalTime": "09:30 PM",
        "date": "2026-09-26",
        "price": 3050,
        "availableSeats": 40
    },
    {
        "flightNumber": "PX148",
        "airline": "Phoenix Airlines",
        "source": "Lucknow",
        "destination": "Mumbai",
        "departureTime": "08:00 PM",
        "arrivalTime": "11:30 PM",
        "date": "2026-09-27",
        "price": 3225,
        "availableSeats": 45
    },
    {
        "flightNumber": "PX149",
        "airline": "Phoenix Airlines",
        "source": "Chennai",
        "destination": "Bangalore",
        "departureTime": "06:00 AM",
        "arrivalTime": "07:00 AM",
        "date": "2026-09-28",
        "price": 3400,
        "availableSeats": 10
    },
    {
        "flightNumber": "PX150",
        "airline": "Phoenix Airlines",
        "source": "Delhi",
        "destination": "Hyderabad",
        "departureTime": "07:15 AM",
        "arrivalTime": "08:45 AM",
        "date": "2026-09-29",
        "price": 3575,
        "availableSeats": 15
    }
];

module.exports = flights;